#ifndef __USE_PPUSDK__
  #define gpuMalloc                          cudaMalloc
  #define gpuMallocHost                      cudaMallocHost
  #define gpuFree                            cudaFree
  #define gpuFreeHost                        cudaFreeHost
  #define gpuMemset                          cudaMemset
  #define gpuMemcpy                          cudaMemcpy
  #define gpuMemcpyDeviceToDevice            cudaMemcpyDeviceToDevice
  #define gpuMemcpyHostToDevice              cudaMemcpyHostToDevice
  #define gpuMemcpyDeviceToHost              cudaMemcpyDeviceToHost
  #define gpuHostGetDevicePointer            cudaHostGetDevicePointer
  #define gpuGetDeviceCount                  cudaGetDeviceCount
  #define gpuGetLastError                    cudaGetLastError
  #define gpuGetErrorString                  cudaGetErrorString
  #define gpuDeviceGetAttribute              cudaDeviceGetAttribute
  #define gpuDevAttrComputeMode              cudaDevAttrComputeMode
  #define gpuComputeModeProhibited           cudaComputeModeProhibited
  #define gpuDevAttrComputeCapabilityMajor   cudaDevAttrComputeCapabilityMajor
  #define gpuDevAttrComputeCapabilityMinor   cudaDevAttrComputeCapabilityMinor
  #define gpuSetDevice                       cudaSetDevice
  #define gpuGetDeviceProperties             cudaGetDeviceProperties
  #define gpuDeviceProp                      cudaDeviceProp
  #define GPfunction                         CUfunction
#else
  #define gpuMalloc                          hggcMalloc
  #define gpuMallocHost                      hggcMallocHost
  #define gpuFree                            hggcFree
  #define gpuFreeHost                        hggcFreeHost
  #define gpuMemset                          hggcMemset
  #define gpuMemcpy                          hggcMemcpy
  #define gpuMemcpyDeviceToDevice            hggcMemcpyDeviceToDevice
  #define gpuMemcpyHostToDevice              hggcMemcpyHostToDevice
  #define gpuMemcpyDeviceToHost              hggcMemcpyDeviceToHost
  #define gpuHostGetDevicePointer            hggcHostGetDevicePointer
  #define gpuGetDeviceCount                  hggcGetDeviceCount
  #define gpuGetLastError                    hggcGetLastError
  #define gpuGetErrorString                  hggcGetErrorString
  #define gpuDeviceGetAttribute              hggcDeviceGetAttribute
  #define gpuDevAttrComputeMode              hggcDevAttrComputeMode
  #define gpuComputeModeProhibited           hggcComputeModeProhibited
  #define gpuDevAttrComputeCapabilityMajor   hggcDevAttrComputeCapabilityMajor
  #define gpuDevAttrComputeCapabilityMinor   hggcDevAttrComputeCapabilityMinor
  #define gpuSetDevice                       hggcSetDevice
  #define gpuGetDeviceProperties             hggcGetDeviceProperties
  #define gpuDeviceProp                      hggcDeviceProp
  #define GPfunction                         HGfunction
#endif