#ifndef COMPATIBLE_WRAPPER_H
#define COMPATIBLE_WRAPPER_H

/*
 * compatible_wrapper.h — Compatibility layer for PPU
 *
 * Provides COMPATIBLE_XXX version macros, COMPATIBLE_ARCH define,
 * and compatibleXxx GetVersion API stubs for code converted by sailify.
 *
 * Generated by sailify with version config:
 *   CUDA: {cuda_str}, cuBLAS: {cublas_str}, cuFFT: {cufft_str},
 *   cuRAND: {curand_str}, cuSPARSE: {cusparse_str}, cuSOLVER: {cusolver_str},
 *   cuDNN: {cudnn_str}, NCCL: {nccl_str},
 *   Video: {video_str}, CUPTI: {cupti_ver}, NPP: {npp_major}.{npp_minor}.{npp_build}
 */

#include <stdio.h>
#include <stdlib.h>
#include <hggc.h>

/* ── PPU SDK version ──
 * Resolved by sailify ({ppu_sdk_str} here); 0 = unknown keeps the legacy
 * behavior.  Override at compile time with
 * -DPPU_SDK_VERSION=<major>*10000+<minor>*100+<patch>. */
#ifndef PPU_SDK_VERSION_MAJOR
#define PPU_SDK_VERSION_MAJOR {ppu_sdk_major}
#endif
#ifndef PPU_SDK_VERSION_MINOR
#define PPU_SDK_VERSION_MINOR {ppu_sdk_minor}
#endif
#ifndef PPU_SDK_VERSION_PATCH
#define PPU_SDK_VERSION_PATCH {ppu_sdk_patch}
#endif
#ifndef PPU_SDK_VERSION
#define PPU_SDK_VERSION ((PPU_SDK_VERSION_MAJOR) * 10000 \
                         + (PPU_SDK_VERSION_MINOR) * 100 \
                         + (PPU_SDK_VERSION_PATCH))
#endif

/* PPU SDK fixups — must come before other PPU SDK headers */
#include "ppu_sdk_fixups.h"

/* PPU SDK headers — C++ only (pure C third-party code may conflict) */
#if defined(__cplusplus)

#include <hgpti_result.h>
#include <hgrtc.h>
#include <hgJitLink.h>
#include <hgTIXCompiler.h>
#include <acblas_v2.h>
#include <acfft.h>
#include <acrand.h>
#include <acsparse.h>
#include <acsolver_common.h>
#include <acsolverDn.h>
#include <acdnn.h>
#include <hgml.h>
#include <hgpti_checkpoint.h>
#include <hgpti_pcsampling_util.h>
#include <hggc_library_types.h>
#include <hgppdefs.h>
#include <hgppcore.h>

#endif /* __cplusplus */

/* PPU SDK fixups (post-include phase) */
#define PPU_SDK_FIXUPS_POST
#include "ppu_sdk_fixups.h"

/* ── Version macros ── */

#define COMPATIBLE_VERSION         {cuda_ver}
#define COMPATIBLE_RT_VERSION      {cuda_ver}
#define COMPATIBLE_DNN_VERSION    {cudnn_ver}
#define COMPATIBLE_BLAS_VERSION   {cublas_ver}
#define COMPATIBLE_FFT_VERSION    {cufft_ver}
#define COMPATIBLE_RAND_VERSION   {curand_ver}
#define COMPATIBLE_SPARSE_VERSION {cusparse_ver}
#define COMPATIBLE_SOLVER_VERSION {cusolver_ver}
#define COMPATIBLE_NCCL_VERSION    {nccl_ver}
#define COMPATIBLE_CUPTI_VERSION      {cupti_ver}
#define COMPATIBLE_VIDEO_VERSION  {video_ver}

#define COMPATIBLE_NPP_MAJOR       {npp_major}
#define COMPATIBLE_NPP_MINOR       {npp_minor}
#define COMPATIBLE_NPP_BUILD       {npp_build}

#define COMPATIBLE_DNN_MAJOR        {cudnn_major}
#define COMPATIBLE_DNN_MINOR        {cudnn_minor}
#define COMPATIBLE_DNN_PATCHLEVEL   {cudnn_patch}

#define COMPATIBLE_BLAS_MAJOR       {cublas_major}
#define COMPATIBLE_BLAS_MINOR       {cublas_minor}
#define COMPATIBLE_BLAS_PATCHLEVEL  {cublas_patch}

#define COMPATIBLE_FFT_MAJOR        {cufft_major}
#define COMPATIBLE_FFT_MINOR        {cufft_minor}
#define COMPATIBLE_FFT_PATCH        {cufft_patch}

#define COMPATIBLE_RAND_MAJOR       {curand_major}
#define COMPATIBLE_RAND_MINOR       {curand_minor}
#define COMPATIBLE_RAND_PATCH       {curand_patch}

#define COMPATIBLE_SPARSE_MAJOR     {cusparse_major}
#define COMPATIBLE_SPARSE_MINOR     {cusparse_minor}
#define COMPATIBLE_SPARSE_PATCH     {cusparse_patch}

#define COMPATIBLE_SOLVER_MAJOR     {cusolver_major}
#define COMPATIBLE_SOLVER_MINOR     {cusolver_minor}
#define COMPATIBLE_SOLVER_PATCH     {cusolver_patch}

#define COMPATIBLE_NCCL_MAJOR       {nccl_major}
#define COMPATIBLE_NCCL_MINOR       {nccl_minor}
#define COMPATIBLE_NCCL_PATCH       {nccl_patch}

#define COMPATIBLE_NCCL_VERSION_CALC(X,Y,Z) ((X)*10000 + (Y)*100 + (Z))

#define __COMPATIBLECC_VER_MAJOR__  {cuda_major}
#define __COMPATIBLECC_VER_MINOR__  {cuda_minor}
#define __COMPATIBLECC_VER_BUILD__  {cuda_patch}

/* ── Architecture mapping ── */

/* COMPATIBLE_ARCH mirrors __CUDA_ARCH__: device-only.
 * Do NOT use __HGGCCC__ here — it's defined for all -x cu code. */
#if defined(__HGGC_ARCH__)
  #ifndef COMPATIBLE_ARCH
    #if __HGGC_ARCH__ == 100
      #define COMPATIBLE_ARCH 800
    #elif __HGGC_ARCH__ == 150
      #define COMPATIBLE_ARCH 890
    #else
      #define COMPATIBLE_ARCH __HGGC_ARCH__
    #endif
  #endif
#endif

/* COMPATIBLE_ARCH_LIST mirrors __CUDA_ARCH_LIST__: only defined by hgcc,
 * not by plain g++. */
#ifndef COMPATIBLE_ARCH_LIST
  #if defined(__HGGCCC__)
    #if defined(COMPATIBLE_ARCH)
      #define COMPATIBLE_ARCH_LIST COMPATIBLE_ARCH
    #else
      #define COMPATIBLE_ARCH_LIST 800
    #endif
  #endif
#endif

/* ── GetVersion API stubs ── */

#if defined(__cplusplus)

#ifdef __cplusplus
extern "C" {{
#endif

static inline hggcError_t compatibleDriverGetVersion(int *driverVersion) {{
    if (driverVersion) *driverVersion = COMPATIBLE_VERSION;
    return (hggcError_t)0;
}}

/* cuDriverGetVersion is a driver API entry point: it returns HGresult (see
 * hggc.h), not hggcError_t, so it cannot share compatibleDriverGetVersion.
 * It still reports COMPATIBLE_VERSION (not the PPU driver version) so that
 * CUDA-style version checks keep working. */
static inline HGresult compatDriverGetVersion(int *driverVersion) {{
    if (driverVersion) *driverVersion = COMPATIBLE_VERSION;
    return HGGC_SUCCESS;
}}

static inline hggcError_t compatibleRuntimeGetVersion(int *runtimeVersion) {{
    if (runtimeVersion) *runtimeVersion = COMPATIBLE_RT_VERSION;
    return (hggcError_t)0;
}}

static inline acblasStatus_t compatibleBlasGetVersion(acblasHandle_t handle, int *version) {{
    (void)handle;
    if (version) *version = COMPATIBLE_BLAS_VERSION;
    return (acblasStatus_t)0;
}}

static inline size_t compatibleBlasLtGetVersion(void) {{
    return (size_t)COMPATIBLE_BLAS_VERSION;
}}

static inline size_t compatibleBlasLtGetCudartVersion(void) {{
    return (size_t)COMPATIBLE_VERSION;
}}

static inline size_t compatibleDnnGetVersion(void) {{
    return (size_t)COMPATIBLE_DNN_VERSION;
}}

static inline size_t compatibleDnnGetCudartVersion(void) {{
    return (size_t)COMPATIBLE_VERSION;
}}

static inline hgrtcResult compatiblertcVersion(int *major, int *minor) {{
    if (major) *major = COMPATIBLE_VERSION / 1000;
    if (minor) *minor = (COMPATIBLE_VERSION / 100) % 10;
    return (hgrtcResult)0;
}}

static inline hgJitLinkResult compatibleJitLinkGetVersion(unsigned int *major, unsigned int *minor) {{
    if (major) *major = COMPATIBLE_VERSION / 1000;
    if (minor) *minor = (COMPATIBLE_VERSION / 100) % 10;
    return (hgJitLinkResult)0;
}}

static inline hgTIXCompileResult compatiblePTXCompilerGetVersion(unsigned int *major, unsigned int *minor) {{
    if (major) *major = COMPATIBLE_VERSION / 1000;
    if (minor) *minor = (COMPATIBLE_VERSION / 100) % 10;
    return (hgTIXCompileResult)0;
}}

static inline acrandStatus_t compatibleRandGetVersion(int *version) {{
    if (version) *version = COMPATIBLE_RAND_VERSION;
    return (acrandStatus_t)0;
}}

static inline acfftResult compatibleFftGetVersion(int *version) {{
    if (version) *version = COMPATIBLE_FFT_VERSION;
    return (acfftResult)0;
}}

static inline acsparseStatus_t compatibleSparseGetVersion(acsparseHandle_t handle, int *version) {{
    (void)handle;
    if (version) *version = COMPATIBLE_SPARSE_VERSION;
    return (acsparseStatus_t)0;
}}

static inline acsolverStatus_t compatibleSolverGetVersion(int *version) {{
    if (version) *version = COMPATIBLE_SOLVER_VERSION;
    return (acsolverStatus_t)0;
}}

/* Macro so pcclResult_t resolves at point of use (pccl.h not included here) */
#define compatibleNcclGetVersion(v) \
    ((void)((v) ? (void)(*(v) = COMPATIBLE_NCCL_VERSION) : (void)0), \
     static_cast<pcclResult_t>(0))

static inline HGptiResult compatibleCuptiGetVersion(unsigned int *version) {{
    if (version) *version = COMPATIBLE_CUPTI_VERSION;
    return (HGptiResult)0;
}}

static inline int compatibleVideoGetVersion(unsigned int *version) {{
    if (version) *version = COMPATIBLE_VIDEO_VERSION;
    return 0;
}}

static inline const HGppLibraryVersion* compatiblePpGetLibVersion(void) {{
    static const HGppLibraryVersion v = {{
        COMPATIBLE_NPP_MAJOR,
        COMPATIBLE_NPP_MINOR,
        COMPATIBLE_NPP_BUILD,
    }};
    return &v;
}}

#ifdef __cplusplus
}}
#endif

/* ── GetProperty API stubs ── */

#ifdef __cplusplus
extern "C" {{
#endif

/* cuDNN/cuFFT/cuRAND/cuSPARSE/cuSOLVER: major*1000 + minor*100 + patch */
static inline int _compatible_extract_property_std(int version, hggcLibraryPropertyType type) {{
    if (type == HGGC_MAJOR_VERSION) return version / 1000;
    if (type == HGGC_MINOR_VERSION) return (version / 100) % 10;
    if (type == HGGC_PATCH_LEVEL) return version % 100;
    return 0;
}}

/* cuBLAS: major*10000 + minor*100 + patch */
static inline int _compatible_extract_property_cublas(int version, hggcLibraryPropertyType type) {{
    if (type == HGGC_MAJOR_VERSION) return version / 10000;
    if (type == HGGC_MINOR_VERSION) return (version / 100) % 100;
    if (type == HGGC_PATCH_LEVEL) return version % 100;
    return 0;
}}

static inline acdnnStatus_t compatibleDnnGetProperty(hggcLibraryPropertyType type, int *value) {{
    if (value) *value = _compatible_extract_property_std(COMPATIBLE_DNN_VERSION, type);
    return (acdnnStatus_t)0;
}}

static inline acblasStatus_t compatibleBlasGetProperty(hggcLibraryPropertyType type, int *value) {{
    if (value) *value = _compatible_extract_property_cublas(COMPATIBLE_BLAS_VERSION, type);
    return (acblasStatus_t)0;
}}

static inline acfftResult compatibleFftGetProperty(hggcLibraryPropertyType type, int *value) {{
    if (value) *value = _compatible_extract_property_std(COMPATIBLE_FFT_VERSION, type);
    return (acfftResult)0;
}}

static inline acrandStatus_t compatibleRandGetProperty(hggcLibraryPropertyType type, int *value) {{
    if (value) *value = _compatible_extract_property_std(COMPATIBLE_RAND_VERSION, type);
    return (acrandStatus_t)0;
}}

static inline acsolverStatus_t compatibleSolverGetProperty(hggcLibraryPropertyType type, int *value) {{
    if (value) *value = _compatible_extract_property_std(COMPATIBLE_SOLVER_VERSION, type);
    return (acsolverStatus_t)0;
}}

/* ── Unsupported API stubs (auto-generated) ── */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#include "ppu_unsupported_stubs.h"
#pragma GCC diagnostic pop
#ifdef __cplusplus
}}
#endif

#endif /* __cplusplus */

#endif /* COMPATIBLE_WRAPPER_H */
