"""
nvcc → hgcc compiler flag mapping table.

Each option maps to a dict with keys:
    short        : short-form flag (also registered as a lookup key)
    map_to       : replacement flag(s) — string or list of strings
    needs_ignore : if True, drop the flag (and its value when needs_value)
    needs_value  : if True, the next argument is the option's value
    value_map    : dict mapping raw value → replacement value (or {needs_ignore: True})
"""

NVCC_HGCC_OPTIONS: dict[str, dict] = {
    # ── Direct mappings ──
    '--cubin':                      {'short': '-cubin',                      'map_to': '-hgbin'},
    '--ptx':                        {'short': '-ptx',                         'map_to': '-hgbin'},
    '--cuda':                       {'short': '-cuda',                        'map_to': '-hggc'},
    '--extended-lambda':            {'short': '-extended-lambda',             'map_to': ['--extended-lambda', '-D__HGGCCC_EXTENDED_LAMBDA__']},
    '--expt-extended-lambda':       {'short': '-expt-extended-lambda',        'map_to': ['--extended-lambda', '-D__HGGCCC_EXTENDED_LAMBDA__']},
    '--device-debug':               {'short': '-G',                           'map_to': ['-G', '-D__CUDACC_DEBUG__']},
    '--device-w':                   {'short': '-dw',                          'map_to': ['-c', '-rdc=false']},
    '--nvlink-options':             {'short': '-Xnvlink',                    'map_to': '--hglink-options',            'needs_value': True},
    '--fatbin-options':             {'short': '-Xfatbin',                     'map_to': '--hgfatbinary-options',       'needs_value': True},
    '--forward-unknown-opts':       {'short': '-forward-unknown-opts',        'map_to': ['--forward-unknown-to-host-linker', '--forward-unknown-to-host-compiler']},
    '--relocatable-link':           {'short': '-r',                           'map_to': '-r'},
    '--compiler-options':           {'short': '-Xcompiler',                   'map_to': '-Xcompiler',                 'needs_value': True},
    '--linker-options':             {'short': '-Xlinker',                     'map_to': '-Xlinker',                   'needs_value': True},
    '--archive-optionss':           {'short': '-Xarchive',                    'map_to': '-Xarchive',                  'needs_value': True},
    '-mllvm':                       {'map_to': '-Xllvm',                                                              'needs_value': True},
    '--dopt':                       {'short': '-dopt',                        'map_to': '-dopt',                       'needs_value': True,
                                   'value_map': {'off': 0, 'on': 3}},
    '--ptxas-options':              {'short': '-Xptxas',                      'map_to': '--llvm-options',              'needs_value': True,
                                   'value_map': {
                                       '-warn-spills': '-ppu-warn-spills',
                                       '--warn-on-spills': '-ppu-warn-spills',
                                       '--warn-on-double-precision-use': '-ppu-warn-double-usage',
                                       '-warn-double-usage': '-ppu-warn-double-usage',
                                       '--warn-on-local-memory-usage': '-ppu-warn-lmem-usage',
                                       '-warn-lmem-usage': '-ppu-warn-lmem-usage',
                                       '-suppress-stack-size-warning': '-ppu-suppress-stack-size-warning',
                                       '--suppress-stack-size-warning': '-ppu-suppress-stack-size-warning',
                                       '--def-load-cache=ca': '-ppu-dlcm=0',
                                       '--def-load-cache=cg': '-ppu-dlcm=2',
                                       '--def-load-cache=cv': '-ppu-dlcm=3',
                                       '--def-load-cache=cs': '-ppu-dlcm=4',
                                       '--def-load-cache=lu': '-ppu-dlcm=5',
                                       '--def-load-cache=wb': '-ppu-dlcm=0',
                                       '--def-load-cache=wt': '-ppu-dlcm=3',
                                       '-dlcm=ca': '-ppu-dlcm=0',
                                       '-dlcm=cg': '-ppu-dlcm=2',
                                       '-dlcm=cv': '-ppu-dlcm=3',
                                       '-dlcm=cs': '-ppu-dlcm=4',
                                       '-dlcm=lu': '-ppu-dlcm=5',
                                       '-dlcm=wb': '-ppu-dlcm=0',
                                       '-dlcm=wt': '-ppu-dlcm=3',
                                       '--def-store-cache=ca': '-ppu-dscm=0',
                                       '--def-store-cache=cg': '-ppu-dscm=2',
                                       '--def-store-cache=cv': '-ppu-dscm=3',
                                       '--def-store-cache=cs': '-ppu-dscm=4',
                                       '--def-store-cache=lu': '-ppu-dscm=5',
                                       '--def-store-cache=wb': '-ppu-dscm=0',
                                       '--def-store-cache=wt': '-ppu-dscm=3',
                                       '-dscm=ca': '-ppu-dscm=0',
                                       '-dscm=cg': '-ppu-dscm=2',
                                       '-dscm=cv': '-ppu-dscm=3',
                                       '-dscm=cs': '-ppu-dscm=4',
                                       '-dscm=lu': '-ppu-dscm=5',
                                       '-dscm=wb': '-ppu-dscm=0',
                                       '-dscm=wt': '-ppu-dscm=3',
                                       '--force-load-cache=ca': '-ppu-flcm=0',
                                       '--force-load-cache=cg': '-ppu-flcm=2',
                                       '--force-load-cache=cv': '-ppu-flcm=3',
                                       '--force-load-cache=cs': '-ppu-flcm=4',
                                       '--force-load-cache=lu': '-ppu-flcm=5',
                                       '--force-load-cache=wb': '-ppu-flcm=0',
                                       '--force-load-cache=wt': '-ppu-flcm=3',
                                       '-flcm=ca': '-ppu-flcm=0',
                                       '-flcm=cg': '-ppu-flcm=2',
                                       '-flcm=cv': '-ppu-flcm=3',
                                       '-flcm=cs': '-ppu-flcm=4',
                                       '-flcm=lu': '-ppu-flcm=5',
                                       '-flcm=wb': '-ppu-flcm=0',
                                       '-flcm=wt': '-ppu-flcm=3',
                                       '--force-store-cache=ca': '-ppu-fscm=0',
                                       '--force-store-cache=cg': '-ppu-fscm=2',
                                       '--force-store-cache=cv': '-ppu-fscm=3',
                                       '--force-store-cache=cs': '-ppu-fscm=4',
                                       '--force-store-cache=lu': '-ppu-fscm=5',
                                       '--force-store-cache=wb': '-ppu-fscm=0',
                                       '--force-store-cache=wt': '-ppu-fscm=3',
                                       '-fscm=ca': '-ppu-fscm=0',
                                       '-fscm=cg': '-ppu-fscm=2',
                                       '-fscm=cv': '-ppu-fscm=3',
                                       '-fscm=cs': '-ppu-fscm=4',
                                       '-fscm=lu': '-ppu-fscm=5',
                                       '-fscm=wb': '-ppu-fscm=0',
                                       '-fscm=wt': '-ppu-fscm=3',
                                       '--verbose': {'needs_ignore': True},
                                       '-v': {'needs_ignore': True},
                                       '-disable-optimizer-consts': {'needs_ignore': True},
                                       '--disable-optimizer-consts': {'needs_ignore': True},
                                   }},

    # ── Ignored flags (dropped silently) ──
    '--no-display-error-number':           {'short': '-no-err-no',                          'needs_ignore': True},
    '--no-align-double':                                                                   {'needs_ignore': True},
    '--source-in-ptx':                     {'short': '-src-in-ptx',                         'needs_ignore': True},
    '--extra-device-vectorization':        {'short': '-extra-device-vectorization',          'needs_ignore': True},
    '--target-directory':                  {'short': '-target-dir',                         'needs_ignore': True,  'needs_value': True},
    '--diag-suppress':                     {'short': '-diag-suppress',                      'needs_ignore': True,  'needs_value': True},
    '--cudafe-options':                   {'short': '-Xcudafe',                            'needs_ignore': True,  'needs_value': True},
    '--objdir-as-tempdir':                 {'short': '-objtemp',                            'needs_ignore': True},
    '--Ofast-compil':                      {'short': '-ofc',                               'needs_ignore': True},
    '--gen-opt-lto':                       {'short': '-gen-opt-lto',                        'needs_ignore': True},
    '--no-host-device-initializer-list':   {'short': '-nohdinitlist',                       'needs_ignore': True},
    '--no-host-device-move-forward':       {'short': '-nohdmoveforward',                    'needs_ignore': True},
    '--device-entity-has-hidden-visibility': {'short': '-device-entity-has-hidden-visibility', 'needs_ignore': True, 'needs_value': True},
    '--dont-use-profile':                  {'short': '-noprof',                             'needs_ignore': True},
    '--split-compile':                     {'short': '-split-compile',                      'needs_ignore': True,  'needs_value': True},
    '--split-compile-extended':            {'short': '-split-compile-extended',             'needs_ignore': True,  'needs_value': True},
    '--fdevice-syntax-only':               {'short': '-fdevice-syntax-only',                'needs_ignore': True},
    '--fdevice-time-trace':                {'short': '-fdevice-time-trace',                 'needs_ignore': True,  'needs_value': True},
    '--time':                              {'short': '-time',                               'needs_ignore': True,  'needs_value': True},
    '--entries':                           {'short': '-e',                                  'needs_ignore': True,  'needs_value': True},
    '--Wext-lambda-captures-this':         {'short': '-Wext-lambda-captures-this',          'needs_ignore': True},
    '--Wno-deprecated-declarations':       {'short': '-Wno-deprecated-declarations',        'needs_ignore': True},
    '--Wno-deprecated-gpu-targets':        {'short': '-Wno-deprecated-gpu-targets',         'needs_ignore': True},
    '--extensible-whole-program':          {'short': '-ewp',                                'needs_ignore': True},
    '--display-error-number':              {'short': '-err-no',                             'needs_ignore': True},
    '--diag-error':                        {'short': '-diag-error',                         'needs_ignore': True,  'needs_value': True},
    '--diag-warn':                         {'short': '-diag-warn',                          'needs_ignore': True,  'needs_value': True},
    '--host-linker-script':                {'short': '-hls',                                'needs_ignore': True,  'needs_value': True},
    '--augment-host-linker-script':        {'short': '-aug-hls',                            'needs_ignore': True},
    '--brief-diagnostic':                  {'short': '-brief-diag',                         'needs_ignore': True,  'needs_value': True},
    '--jump-table-density':                {'short': '-jtd',                                'needs_ignore': True,  'needs_value': True},
    '--relocatable-ptx':                   {'short': '-reloc-ptx',                          'needs_ignore': True},
    '--device-stack-protector':            {'short': '-device-stack-protector',             'needs_ignore': True,  'needs_value': True},
    '--frandom-seed':                      {'short': '-frandom-seed',                       'needs_ignore': True,  'needs_value': True},
    '--sanitize':                          {'short': '-sanitize',                           'needs_ignore': True,  'needs_value': True},
    '--jobserver':                         {'short': '-jobserver',                          'needs_ignore': True},
    '--allow-unsupported-compiler':        {'short': '-allow-unsupported-compiler',         'needs_ignore': True},
    '--cudadevrt':                         {'short': '-cudadevrt',                          'needs_ignore': True,  'needs_value': True},
    '--no-hggc-embed-bc':                  {'short': '-no-hggc-embed-bc',                   'needs_ignore': True},
    '--options-file':                      {'short': '-optf',                               'needs_ignore': True},
}
